### ISSUE TITLE
Add teams to ignore section

### ISSUE THREAD

**Issue by frozzare** [frozzare/hellobot#1]
Would be nice if we could ignore teams as well. Documentation for teams api: https://developer.github.com/v3/repos/#list-teams

```yaml
ignore:
    teams:
        - core
```
